version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: song_postgres
    restart: always
    environment:
      POSTGRES_USER: songuser
      POSTGRES_PASSWORD: songpass
      POSTGRES_DB: songdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: